Repository YAPP-Github/20th-ALL-Rounder-Team-2-Web, pull requests merged in 2022-07, with the labels that each got.

#50 #48 feat: 홈(메인) 페이지 클래스 리스트 API 연동
  .env.development
  .env.production
  .eslintrc
  jest.config.js
  jest.setup.js
  next.config.js
  package-lock.json
  package.json
  src/api/customAxios.ts
  src/api/hello.ts
  src/api/index.ts
  src/components/Common/Layout/Layout/Layout.tsx
  src/components/Common/Layout/Layout/LayoutStyle.ts
  src/components/Common/Layout/Section/Section.tsx
  src/components/Common/Layout/Section/SectionStyle.ts
  src/components/Common/Layout/index.ts
  src/components/Home/LectureCard/LectureCard.tsx
  src/components/Home/LectureCard/LectureCardStyle.ts
  src/components/Home/LectureList/LectureList.tsx
  src/components/Home/tests/LectureList.test.tsx
  src/hooks/home/useLectureInfo.ts
  src/hooks/index.ts
  src/mocks/handlers.js
  src/mocks/mockData/lectureInfo.js
  src/mocks/server.js
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/category/index.tsx
  src/pages/class-detail/[id].tsx
  src/pages/index.tsx
  src/pages/profile/[id].tsx
  src/pages/review/[idx].tsx
  src/react-query/keys.ts
  src/react-query/queryClient.ts
  src/setupTests.js
  src/test-utils/index.tsx
  src/types/index.ts
  src/types/lectureInfo.ts
Labels: feature, Page

#54 #53 feat: 폰트 최적화
  src/styles/font.ts
Labels: feature

#55 #51 feat: 카테고리 별 클래스 목록 조회 기능 구현
  jest.config.js
  package-lock.json
  package.json
  src/__tests__/category/useInfiniteLecture.test.tsx
  src/__tests__/home/LectureList.test.tsx
  src/__tests__/home/useLectureInfo.test.tsx
  src/api/index.ts
  src/components/Home/Category/Category.tsx
  src/components/Home/LectureCard/LectureCardStyle.ts
  src/components/Home/LectureList/LectureList.tsx
  src/components/Home/tests/LectureList.test.tsx
  src/constants/categoryList.ts
  src/hooks/home/useInfiniteLecture.ts
  src/hooks/home/useLectureInfo.ts
  src/mocks/mockData/categoryLecture.js
  src/pages/_app.tsx
  src/pages/category/index.tsx
  src/types/lectureInfo.ts
  tsconfig.json
Labels: feature, Component, Page

#58 #57 feat: 도커 파일 RUN 명령어 수정
  Dockerfile
Labels: feature

#59 #31 feat: 매칭 신청서 레이아웃
  public/img/matching.png
  src/components/Common/Forms/TextArea/TextArea.tsx
  src/components/Matching/FirstStep/FirstStep.tsx
  src/components/Matching/FirstStep/FirstStepStyle.ts
  src/components/Matching/LastStep/LastStep.tsx
  src/components/Matching/LastStep/LastStepStyle.ts
  src/components/Matching/MatchingStyle.ts
  src/components/Matching/ScheduleBox/ScheduleBox.tsx
  src/components/Matching/ScheduleBox/ScheduleBoxStyle.ts
  src/components/Matching/SecondStep/SecondStep.tsx
  src/components/Matching/SecondStep/SecondStepStyle.ts
  src/components/Matching/Title/Title.tsx
  src/components/Matching/Title/TitleStyle.ts
  src/components/Matching/index.ts
  src/hooks/index.ts
  src/hooks/useSelect.ts
  src/pages/class-detail/[id].tsx
  src/pages/matching/index.tsx
  src/recoil/matching/atoms.ts
  src/store/index.ts
Labels: help wanted, feature, Page

#61 #60 fix: 리뷰 페이지 배포 오류 수정
  src/components/Common/Forms/TextArea/TextArea.tsx
  src/pages/review/[idx].tsx
Labels: bug

#62 #49 refactor: 강의 관련 네이밍 lecture로 수정
  package-lock.json
  src/components/LectureDetail/CoachProfile/CoachProfile.tsx
  src/components/LectureDetail/CoachProfile/CoachProfileStyle.ts
  src/components/LectureDetail/Guideline/Guideline.tsx
  src/components/LectureDetail/Guideline/GuidelineStyle.ts
  src/components/LectureDetail/HowToUse/HowToUse.tsx
  src/components/LectureDetail/HowToUse/HowToUseStyle.ts
  src/components/LectureDetail/LectureDetailStyle.ts
  src/components/LectureDetail/LectureInfo/LectureImages.tsx
  src/components/LectureDetail/LectureInfo/LectureInfo.tsx
  src/components/LectureDetail/LectureInfo/LectureInfoStyles.ts
  src/components/LectureDetail/index.ts
  src/components/Matching/LastStep/LastStep.tsx
  src/components/Profile/LectureReview/LectureReview.tsx
  src/components/Profile/LectureReview/LectureReviewStyle.ts
  src/components/Profile/LectureReview/Review.tsx
  src/components/Profile/index.ts
  src/pages/lecture-detail/[id].tsx
  src/pages/profile/[id].tsx
Labels: refactor

#65 #52 feat: 최근 등록된 클래스 검색 기능 추가
  public/img/empty-data.png
  src/components/Common/Header/Header.tsx
  src/components/Common/Header/HeaderStyle.ts
  src/components/Common/Layout/Layout/Layout.tsx
  src/components/Common/Layout/Layout/LayoutStyle.ts
  src/components/Common/Layout/PageLayout/PageLayout.tsx
  src/components/Common/Layout/PageLayout/PageLayoutStyle.ts
  src/components/Common/Layout/index.ts
  src/components/Common/SearchBar/SearchBar.tsx
  src/components/Common/index.ts
  src/components/Home/EmptyLectureList/EmptyLectureList.tsx
  src/components/Home/EmptyLectureList/EmptyLectureListStyle.ts
  src/components/Home/LectureList/LectureList.tsx
  src/components/Home/SearchModal/SearchModal.tsx
  src/components/Home/SearchModal/SearchModalStyle.ts
  src/components/Home/index.ts
  src/hooks/home/useInfiniteLecture.ts
  src/pages/category/index.tsx
  src/pages/index.tsx
  src/pages/lecture-detail/[id].tsx
  src/pages/profile/[id].tsx
  src/pages/review/[idx].tsx
  src/recoil/home/atoms.ts
Labels: feature, Style, Component, Page

#70 #56 feat: 클래스 목록 스켈레톤 UI 적용
  src/components/Common/SearchBar/SearchBarStyle.ts
  src/components/Home/LectureCard/LectureCard.tsx
  src/components/Home/LectureCard/LectureCardStyle.ts
  src/components/Home/LectureCard/LoadingCard.tsx
  src/components/Home/LectureCard/LoadingCardStyle.ts
  src/components/Home/LectureList/LoadingList.tsx
  src/components/Home/SearchModal/SearchModal.tsx
  src/components/Home/index.ts
  src/pages/category/index.tsx
  src/pages/index.tsx
Labels: feature, Component, Page

#71 #64 feat: 리뷰 작성 기능
  src/api/index.ts
  src/hooks/review/useRegisterReview.ts
  src/pages/review/[idx].tsx
  src/types/review.ts
Labels: feature, Page

#75 #73 feat: 등록된 클래스 목록에서 상세페이지로 라우팅 연결
  src/components/Home/LectureCard/LectureCard.tsx
  src/components/Home/LectureCard/LectureCardStyle.ts
  src/types/lectureInfo.ts
Labels: feature

#79 #74 feat: 클래스 목록에 태그 및 이미지 값 적용
  next.config.js
  package-lock.json
  package.json
  src/components/Home/LectureCard/LectureCard.tsx
  src/components/Home/LectureCard/LectureCardStyle.ts
  src/components/Home/LectureCard/LoadingCard.tsx
  src/components/Home/LectureCard/LoadingCardStyle.ts
  src/components/Home/LectureList/LectureList.tsx
  src/types/lectureInfo.ts
Labels: feature, Component, Page

#76 #63 feat: 클래스 상세 페이지 API 연동
  package-lock.json
  package.json
  src/api/index.ts
  src/components/LectureDetail/CoachProfile/CoachProfile.tsx
  src/components/LectureDetail/LectureInfo/LectureImages.tsx
  src/components/LectureDetail/LectureInfo/LectureInfo.tsx
  src/hooks/lecture/useLectureDetail.ts
  src/pages/lecture-detail/[id].tsx
  src/react-query/keys.ts
  src/types/lectureDetail.ts
  src/utils/formatSchedule.ts
  src/utils/index.ts
Labels: feature, Page

#82 #80 feat: 클래스 별 카테고리 목록 데이터 SSR 적용
  jest.config.js
  src/__tests__/category/LectureCategory.test.tsx
  src/__tests__/category/useInfiniteLecture.test.tsx
  src/components/Home/Category/Category.tsx
  src/components/Home/LectureCard/LoadingCard.tsx
  src/mocks/handlers.js
  src/mocks/mockData/lectureInfo.js
  src/pages/lecture-category/[id].tsx
  src/test-utils/index.tsx
Labels: feature, Style, Component, Page

#84 #78 feat: 프로필 페이지 API 연동
  package-lock.json
  src/api/index.ts
  src/components/Common/Image/Image.tsx
  src/components/LectureDetail/CoachProfile/CoachProfile.tsx
  src/components/Profile/Introduction/Introduction.tsx
  src/components/Profile/LectureReview/LectureReview.tsx
  src/components/Profile/LectureReview/LectureReviewStyle.ts
  src/components/Profile/LectureReview/Review.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/hooks/profile/useCoachReview.ts
  src/hooks/profile/useProfile.ts
  src/pages/profile/[id].tsx
  src/react-query/keys.ts
  src/types/lectureDetail.ts
  src/types/profile.ts
Labels: feature, Page

#85 #72 feat: 매칭 신청서 작성 기능 구현
  src/api/index.ts
  src/components/Matching/FirstStep/FirstStep.tsx
  src/components/Matching/ScheduleBox/ScheduleBox.tsx
  src/components/Matching/SecondStep/SecondStep.tsx
  src/hooks/matching/useApplyMatching.ts
  src/pages/matching/index.tsx
  src/recoil/matching/atoms.ts
  src/types/matching.ts
Labels: feature, Page

#89 #88 modify: 매칭 신청서 페이지 배포 오류 수정
  src/hooks/matching/useApplyMatching.ts
Labels: bug

#92 #81 feat: 운영클래스 매칭 신청인의 매칭 신청서 페이지 구현
  src/api/index.ts
  src/components/CoachLecture/MatchingPopup/MatchingPopup.tsx
  src/components/CoachLecture/MatchingPopup/MatchingPopupStyle.ts
  src/components/CoachLecture/PlayerInfo/PlayerInfo.tsx
  src/components/CoachLecture/PlayerInfo/PlayerInfoStyle.ts
  src/components/CoachLecture/PlayerSchedule/PlayerSchedule.tsx
  src/components/CoachLecture/PlayerSchedule/PlayerScheduleStyle.ts
  src/components/CoachLecture/PlayerUser/PlayerUser.tsx
  src/components/CoachLecture/PlayerUser/PlayerUserStyle.ts
  src/components/CoachLecture/index.ts
  src/components/Common/Image/Image.tsx
  src/hooks/coachLecture/useMatchingForm.ts
  src/pages/coach-lecture/[id].tsx
  src/react-query/keys.ts
  src/types/coachLecture.ts
  src/utils/formatSchedule.ts
Labels: feature, Style, Component, Page

#90 #88 매칭 신청서 페이지 배포 오류 수정
  src/components/LectureDetail/CoachProfile/CoachProfile.tsx
  src/components/Matching/FirstStep/FirstStep.tsx
  src/hooks/lecture/useLectureDetail.ts
  src/pages/matching/index.tsx
Labels: feature, bug

#94 #87 modify: 클래스 상세 페이지 API 변경 대응
  src/pages/lecture-detail/[id].tsx
  src/types/lectureDetail.ts
Labels: modify

#96 #86 feat: 클래스 상세 페이지 유저 타입과 상태에 따른 CTA 버튼 변경
  src/api/index.ts
  src/components/LectureDetail/LectureDetailStyle.ts
  src/components/LectureDetail/LectureInfo/LectureInfo.tsx
  src/components/LectureDetail/MatchingButton/MatchingButton.tsx
  src/components/LectureDetail/MatchingButton/MatchingButtonStyle.ts
  src/hooks/coachLecture/useMatchingForm.ts
  src/pages/coach-lecture/[id].tsx
  src/pages/lecture-detail/[id].tsx
  src/pages/matching/index.tsx
  src/types/lectureDetail.ts
Labels: feature, Component, Page

#108 #101 feat: 검색 모달창에서 검색 페이지 변경 및 홈화면에서 url 분리
  src/components/Common/Header/Header.tsx
  src/components/Common/SearchBar/SearchBar.tsx
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Home/EmptyLectureList/EmptyLectureList.tsx
  src/components/Home/SearchModal/SearchModal.tsx
  src/components/Home/SearchModal/SearchModalStyle.ts
  src/components/Home/index.ts
  src/pages/index.tsx
  src/pages/lecture-search/index.tsx
  src/recoil/home/atoms.ts
Labels: feature, Page

#104 #103 feat: 후기 작성 페이지 구조 수정
  src/hooks/profile/useProfile.ts
  src/pages/review/index.tsx
Labels: feature

#109 #107 fix: 클래스 상세 페이지 매칭된 사람이 없는 경우 예외처리
  src/components/LectureDetail/MatchingButton/MatchingButton.tsx
Labels: bug

#111 #106 fix: 시간 포맷팅 00분 일 경우 예외처리
  src/utils/formatSchedule.ts
Labels: Style, bug

#113 #105 feat: 후기 작성 페이지 안드로이드 브릿지 연결
  src/api/index.ts
  src/hooks/review/useRegisterReview.ts
  src/types/index.d.ts
Labels: feature, Page

#114 #91 feat: Modal 공통 컴포넌트 추가
  .storybook/main.js
  .storybook/preview.js
  package-lock.json
  package.json
  src/components/CoachLecture/MatchingPopup/MatchingPopup.tsx
  src/components/Common/Button/ButtonStyle.ts
  src/components/Common/Modal/Modal.stories.tsx
  src/components/Common/Modal/Modal.tsx
  src/components/Common/Modal/ModalStyle.ts
  src/components/Common/index.ts
  src/pages/coach-lecture/[id].tsx
  src/styles/styles.d.ts
  src/styles/theme.ts
Labels: feature, Component

#118 #95 feat: 카테고리 목록 조회 시 API 쿼리스트링 변경 대응
  src/__tests__/category/LectureCategory.test.tsx
  src/__tests__/category/useInfiniteLecture.test.tsx
  src/components/Home/Category/Category.tsx
  src/constants/categoryList.ts
  src/mocks/handlers.js
  src/mocks/mockData/lectureInfo.js
  src/pages/lecture-category/[name].tsx
Labels: feature

#117 #100 feat: 가능한 시간대가 없는 경우 예외처리
  package-lock.json
  src/components/LectureDetail/LectureInfo/LectureInfo.tsx
Labels: feature, Page

#119 #115 feat: 검색 페이지 뒤로가기 버튼 브릿지 연결
  src/components/Common/Header/Header.tsx
Labels: feature

#120 #102 feat: 운영클래스 매칭신청서 API 변경 대응
  src/components/CoachLecture/PlayerSchedule/PlayerSchedule.tsx
  src/components/CoachLecture/PlayerSchedule/PlayerScheduleStyle.ts
  src/components/CoachLecture/PlayerUser/PlayerUser.tsx
  src/pages/coach-lecture/[id].tsx
  src/types/coachLecture.ts
Labels: feature, Style, Component

#121 #77 feat: 유저가 볼이 없는 경우 모달 팝업
  src/components/LectureDetail/MatchingButton/MatchingButton.tsx
  src/components/LectureDetail/MatchingButton/MatchingButtonStyle.ts
Labels: feature, Component

#124 #98 feat: 페이지 이동 애니메이션 추가
  package-lock.json
  package.json
  src/components/Common/PageTransition/PageTransition.tsx
  src/components/Common/index.ts
  src/pages/matching/index.tsx
Labels: feature, Style, Page

#133 #126 feat: 홈화면 카테고리 메뉴 여백 스타일 수정
  package-lock.json
  src/components/Common/Header/HeaderStyle.ts
  src/components/Common/SearchBar/SearchBarStyle.ts
  src/components/Home/Category/CategoryStyle.ts
Labels: Style

#140 #127 feat: 검색 페이지 검색 결과 없음 > 홈으로 가기 버튼에 안드로이드 브릿지 연결
  src/components/Home/EmptyLectureList/EmptyLectureList.tsx
Labels: feature

#132 #128 feat: 매칭 신청서 키보드가 버튼이랑 같이 올라오는 버그
  src/components/Common/Forms/TextArea/TextArea.tsx
  src/components/Matching/SecondStep/SecondStep.tsx
  src/components/Matching/SecondStep/SecondStepStyle.ts
Labels: bug

#134 #122 feat: 클래스 상세페이지 CTA 버튼 가운데 정렬
  src/components/LectureDetail/MatchingButton/MatchingButton.tsx
  src/components/LectureDetail/MatchingButton/MatchingButtonStyle.ts
Labels: Style, Page

#137 #129 style: 클래스 상세 페이지 사진 없는 경우 사진 영역 제거
  src/components/LectureDetail/LectureInfo/LectureInfo.tsx
Labels: feature, modify

#141 #139 feat: 홈화면 > 카테고리 목록 페이지 이동 시 안드로이드 브릿지 연결
  src/components/Home/Category/Category.tsx
  src/components/Home/Category/CategoryStyle.ts
  src/types/index.d.ts
Labels: feature

#142 #135 style: 후기가 없는 경우의 박스의 설정된 width값 제거
  src/components/Profile/LectureReview/LectureReviewStyle.ts
Labels: Style

#151 #150 fix: 홈화면 안드로이드 브릿지 수정
  src/components/Home/LectureCard/LectureCard.tsx
  src/types/index.d.ts
Labels: Hotfix, bug

#144 #130 feat: 매칭신청서 안드로이드 브릿지 연결
  src/components/Matching/LastStep/LastStep.tsx
Labels: feature

#146 #145 feat: 매칭 신청 완료 후 보이는 이미지를 background-image 속성으로 수정
  src/components/Matching/LastStep/LastStep.tsx
  src/components/Matching/LastStep/LastStepStyle.ts
  src/components/Matching/SecondStep/SecondStep.tsx
  src/components/Matching/SecondStep/SecondStepStyle.ts
Labels: feature, Style, modify

#149 #148 fix: 매칭신청서 키보드가 열렸을 때 버튼이 화면 위로 올라오는 문제 해결
  src/components/Matching/SecondStep/SecondStep.tsx
Labels: feature, bug

#153 #147 style: 매칭신청서 box width 제거
  src/components/Common/Forms/TextArea/TextAreaStyle.ts
  src/components/Matching/ScheduleBox/ScheduleBoxStyle.ts
  src/components/Matching/Title/TitleStyle.ts
Labels: Style

#156 #154 fix: 마이페이지 링크 연결 안되는 오류 해결
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
Labels: feature, bug

#157 #112 feat: 운영 클래스 매칭 신청인 목록 페이지 작업
  public/img/no-form-list.png
  src/api/index.ts
  src/components/CoachLecture/CoachLectureStyle.ts
  src/components/CoachLecture/FormDetail/MatchingPopup/MatchingPopup.tsx
  src/components/CoachLecture/FormDetail/MatchingPopup/MatchingPopupStyle.ts
  src/components/CoachLecture/FormDetail/PlayerInfo/PlayerInfo.tsx
  src/components/CoachLecture/FormDetail/PlayerInfo/PlayerInfoStyle.ts
  src/components/CoachLecture/FormDetail/PlayerSchedule/PlayerSchedule.tsx
  src/components/CoachLecture/FormDetail/PlayerSchedule/PlayerScheduleStyle.ts
  src/components/CoachLecture/FormDetail/PlayerUser/PlayerUser.tsx
  src/components/CoachLecture/FormDetail/PlayerUser/PlayerUserStyle.ts
  src/components/CoachLecture/FormList/NoFormList/NoFormList.tsx
  src/components/CoachLecture/FormList/NoFormList/NoFormListStyle.ts
  src/components/CoachLecture/FormList/UserFormCard/UserFormCard.tsx
  src/components/CoachLecture/FormList/UserFormCard/UserFormCardStyle.ts
  src/components/CoachLecture/FormList/UserFormList/UserFormList.tsx
  src/components/CoachLecture/index.ts
  src/components/Common/Button/ButtonStyle.ts
  src/hooks/coachLecture/useLectureForms.ts
  src/hooks/coachLecture/useMatchingForm.ts
  src/pages/coach-lecture/[id].tsx
  src/pages/coach-lecture/form-detail/[id].tsx
  src/pages/coach-lecture/on-board/[id].tsx
  src/react-query/keys.ts
  src/types/coachLecture.ts
Labels: feature, Style, Component, Page

#160 #131 feat: 클래스 카테고리별 목록 데이터 응답 속도 개선
  src/pages/lecture-category/[name].tsx
Labels: feature

#162 #161 feat: 운영클래스 매칭 신청인 가능한 시간 정보 추가
  src/components/CoachLecture/FormDetail/PlayerSchedule/PlayerSchedule.tsx
  src/components/CoachLecture/FormList/UserFormCard/UserFormCard.tsx
  src/components/CoachLecture/FormList/UserFormCard/UserFormCardStyle.ts
  src/components/CoachLecture/FormList/UserFormList/UserFormList.tsx
  src/pages/coach-lecture/form-detail/[id].tsx
Labels: feature

#163 #155 feat: 마이페이지 SSR 제거
  src/components/Profile/LectureReview/LectureReview.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/hooks/profile/useCoachReview.ts
  src/hooks/profile/useProfile.ts
  src/pages/profile/[id].tsx
  src/pages/review/index.tsx
Labels: feature

#165 #138 feat: 클래스 상세 페이지 렌더링 속도 개선
  src/components/LectureDetail/MatchingButton/MatchingButton.tsx
  src/hooks/lecture/useLectureDetail.ts
  src/pages/lecture-detail/[id].tsx
  src/pages/matching/index.tsx
Labels: feature

#166 #152 style: 마이페이지 프로필 아이콘 교체
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderStyle.ts
Labels: Style, modify

#169 #167 modify: 사용자 리뷰 프로필 사진 하드코딩 되어있는 부분 수정
  src/components/Profile/LectureReview/Review.tsx
Labels: feature, modify

#173 #172 fix: 마이페이지 소개글 오류 수정
  src/pages/profile/[id].tsx
Labels: bug

#175 #174 feat: 프로필 사진 수정
  src/components/Common/Svg/SvgSprite.tsx
  src/components/Profile/ProfileHeader/ProfileHeader.tsx
  src/components/Profile/ProfileHeader/ProfileHeaderStyle.ts
Labels: feature, Style, Page

#177 #164 feat: 프로필 페이지 skeleton UI 적용
  src/components/Home/LectureCard/LoadingCardStyle.ts
  src/components/Profile/LectureReview/LectureReview.tsx
  src/components/Profile/LectureReview/LoadingReview.tsx
  src/components/Profile/LectureReview/LoadingReviewStyle.ts
Labels: feature

#168 #159 feat: 운영클래스 매칭 신청서 거절/수락 시 안드로이드 브릿지 연결
  src/api/index.ts
  src/components/CoachLecture/FormDetail/MatchingPopup/MatchingPopup.tsx
  src/components/CoachLecture/FormDetail/PlayerUser/PlayerUser.tsx
  src/hooks/coachLecture/useMatchingForm.ts
  src/hooks/coachLecture/usePatchFormState.ts
  src/pages/coach-lecture/form-detail/[id].tsx
  src/types/coachLecture.ts
Labels: feature

#180 #179 feat: 홈화면 최근 등록된 클래스 렌더링 방식 수정
  src/pages/index.tsx
Labels: feature

#182 #181 feat: 클래스 상세 페이지에서 프로필을 클릭했을 때 프로필 페이지로 라우팅
  src/components/LectureDetail/CoachProfile/CoachProfile.tsx
Labels: feature

#183 #178 feat: 클래스 시간 음수로 뜨는 오류 수정
  src/utils/formatSchedule.ts
Labels: feature, bug

#185 #184 style: 클래스 상세 페이지 코치 프로필 스타일 수정
  src/components/LectureDetail/CoachProfile/CoachProfile.tsx
  src/components/LectureDetail/CoachProfile/CoachProfileStyle.ts
Labels: Style

#186 #125 feat: 클래스 상세 페이지 안드로이드 브릿지 연결
  src/components/LectureDetail/MatchingButton/MatchingButton.tsx
Labels: feature

#189 #188 feat: Docker 파일 yarn berry에 맞게 설정 변경
  Dockerfile
Labels: bug

#191 #190 feat: 도커 이미지 이름 설정
  Dockerfile
Labels: bug

#198 #195 feat: yarnberry를 통한 도커 이미지 빌드 시 에러 이슈 해결
  Dockerfile
  packages/knowlly-landing/package.json
Labels: bug
